/*
Deployment script for PartitionsTest

This code was generated by a tool.
Changes to this file may cause incorrect behavior and will be lost if
the code is regenerated.
*/

GO
SET ANSI_NULLS, ANSI_PADDING, ANSI_WARNINGS, ARITHABORT, CONCAT_NULL_YIELDS_NULL, QUOTED_IDENTIFIER ON;

SET NUMERIC_ROUNDABORT OFF;


GO
:setvar DatabaseName "PartitionsTest"
:setvar DefaultFilePrefix "PartitionsTest"
:setvar DefaultDataPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"
:setvar DefaultLogPath "C:\Program Files\Microsoft SQL Server\MSSQL15.MSSQLSERVER\MSSQL\DATA\"

GO
:on error exit
GO
/*
Detect SQLCMD mode and disable script execution if SQLCMD mode is not supported.
To re-enable the script after enabling SQLCMD mode, execute the following:
SET NOEXEC OFF; 
*/
:setvar __IsSqlCmdEnabled "True"
GO
IF N'$(__IsSqlCmdEnabled)' NOT LIKE N'True'
    BEGIN
        PRINT N'SQLCMD mode must be enabled to successfully execute this script.';
        SET NOEXEC ON;
    END


GO
USE [$(DatabaseName)];


GO
PRINT N'Unbinding columns from changing objects on table [dbo].[partitionTable]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_partitionTable] (
    [Timestamp] DATETIME2 (2) NOT NULL
);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[partitionTable])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_partitionTable] ([Timestamp])
        SELECT [Timestamp]
        FROM   [dbo].[partitionTable];
    END

DROP TABLE [dbo].[partitionTable];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_partitionTable]', N'partitionTable';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Dropping SqlPartitionScheme [PS_TEST]...';


GO
DROP PARTITION SCHEME [PS_TEST];


GO
PRINT N'Dropping SqlPartitionFunction [PF_TEST]...';


GO
DROP PARTITION FUNCTION [PF_TEST];


GO
PRINT N'Creating SqlPartitionFunction [PF_TEST]...';


GO
CREATE PARTITION FUNCTION [PF_TEST](DATETIME2 (2))
    AS RANGE
    FOR VALUES ('2023-01-01 00:00:00', '2023-02-01 00:00:00');


GO
PRINT N'Creating SqlPartitionScheme [PS_TEST]...';


GO
CREATE PARTITION SCHEME [PS_TEST]
    AS PARTITION [PF_TEST]
    TO ([PRIMARY], [PRIMARY], [PRIMARY]);


GO
PRINT N'Starting rebuilding table [dbo].[partitionTable]...';


GO
BEGIN TRANSACTION;

SET TRANSACTION ISOLATION LEVEL SERIALIZABLE;

SET XACT_ABORT ON;

CREATE TABLE [dbo].[tmp_ms_xx_partitionTable] (
    [Timestamp] DATETIME2 (2) NOT NULL
) ON [PS_TEST] ([Timestamp]);

IF EXISTS (SELECT TOP 1 1 
           FROM   [dbo].[partitionTable])
    BEGIN
        INSERT INTO [dbo].[tmp_ms_xx_partitionTable] ([Timestamp])
        SELECT [Timestamp]
        FROM   [dbo].[partitionTable];
    END

DROP TABLE [dbo].[partitionTable];

EXECUTE sp_rename N'[dbo].[tmp_ms_xx_partitionTable]', N'partitionTable';

COMMIT TRANSACTION;

SET TRANSACTION ISOLATION LEVEL READ COMMITTED;


GO
PRINT N'Update complete.';


GO
